# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 45590ba861eea69fe2c4dd9d72397ce20108ea8c3ace0751501b7b1fdaffa82f5ca9e5259212f47fdd5749fae09b5731675516a65a197c01839bb3e3bcd5dd51

test:
  secret_key_base: 1f54319dcdce7ee8b4cbd95311784e6f88935c53614fb8aa74e8711fdf9ae1abcb81fdadef34ca73e3cc7bec2dc459386bc370084192b318e9af68fb1fd1f07f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
